theme: jekyll-theme-slate
title: Palash Tyagi's CV
description: <a href="https://drive.google.com/viewer?url=https://raw.githubusercontent.com/Magnus167/resumeCV/master/PTyagi_CV_May22.pdf">View PDF</a> &#124; <a href="https://raw.githubusercontent.com/Magnus167/resumeCV/master/PTyagi_CV_May22.pdf">Download PDF</a> &#124; <a href="https://magnus167.github.io/resumeCV/resume_pdf.htm?src=https://raw.githubusercontent.com/Magnus167/resumeCV/master/resume.md">View Markdown</a>
github:
  is_project_page: false
