theme: jekyll-theme-slate
title: Palash Tyagi's Resume
description: <b><a href="https://docs.google.com/viewer?url=https://raw.githubusercontent.com/Magnus167/resumeCV/master/Resume_PTyagi_May22.pdf">View PDF</a> &#124; <a href="https://raw.githubusercontent.com/Magnus167/resumeCV/master/Resume_PTyagi_May22.pdf">Download PDF</a></b>
